language: go

go:
  - tip
  - 1.x

os:
  - linux
  - osx
  
matrix:
  allow_failures:
    - tip
  fast_finish: true
  
before_install:
  - go get -t -v ./...

script:
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build
  - GOARCH=386 go build
  - go test -race -v ./...
